import Head from 'next/head'

import Carthead from './components/Carthead'

import Cartlist from './components/Cartlist'
export default function cart(){

    return <div className="container max-w-lg ">
         <Head>
            <title>Coffee Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Carthead/>
        <Cartlist/>
      </div>
      
    }